<?php
	$config = Array(
		'base_url' => 'http://t.ake.kr/',
		'uri_segment' => 4,
		'num_links' => 4,
		'per_page' => 1,
		'use_page_numbers' => TRUE,
		'full_tag_open' => '<ul class="pagination">',
		'full_tag_close' => '</ul>',
		'first_link' => '&laquo;',
		'first_tag_open' => '<li>',
		'first_tag_close' => '</li>',
		'prev_link' => '&lt;',
		'prev_tag_open' => '<li>',
		'prev_tag_close' => '</li>',
		'cur_tag_open' => '<li class="active"><a href="#">',
		'cur_tag_close' => '</a></li>',
		'num_tag_open' => '<li>',
		'num_tag_close' => '</li>',
		'next_link' => '&gt;',
		'next_tag_open' => '<li>',
		'next_tag_close' => '</li>',
		'last_link' => '&raquo;',
		'last_tag_open' => '<li>',
		'last_tag_close' => '</li>'
	);